language: python
python:
  - "3.6"
# command to install dependencies

env:
  - DJANGO_VERSION=2.1.7

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt

# command to run tests
script:
  - python manage.py test